logo_url: /logo.svg
media: public/images
output: /images
content:
  - name: posts
    label: Blog Posts
    type: collection
    path: src/content/blog
    create: true
    delete: true
    fields:
      - name: title
        type: string
        label: Post Title
      - label: Draft
        name: draft
        type: boolean
      - label: Author
        name: author
        type: string
      - label: Tags
        name: tags
        type: list
      - label: Image
        name: image
        type: object
        fields:
          - label: Source
            name: src
            type: image
          - label: Alt Text
            name: alt
            type: string
      - label: Snippet
        name: snippet
        type: text
      - label: Publish Date
        name: publishDate
        type: datetime
        format: 'YYYY-MM-DD HH:mm'
      - label: Category
        name: category
        type: select
        options:
          - Tutorials
          - News
          - Reviews
          - Frameworks
      - name: body
        type: markdown
        label: Post Body
